"""
Schedule Models - Data validation for schedule objects

Pydantic models automatically validate data and convert types.
Each model serves a specific purpose:

- Schedule       → Complete schedule (response from API)
- ScheduleCreate → Data needed to create (request body)
- ScheduleUpdate → Optional fields for updating (request body)

Example usage:
    # This will validate the data automatically
    schedule = ScheduleCreate(
        subject="Team Meeting",
        start_time=datetime.now(),
        end_time=datetime.now() + timedelta(hours=1),
    )
"""

from datetime import datetime
from pydantic import BaseModel, Field


class ScheduleBase(BaseModel):
    """
    Base model with common fields.
    
    Other models inherit from this to avoid repetition.
    """
    subject: str = Field(
        ...,  # ... means required
        min_length=1,
        max_length=200,
        description="Event title",
        examples=["Team Meeting"]
    )
    notes: str | None = Field(
        default=None,
        max_length=1000,
        description="Additional notes"
    )
    start_time: datetime = Field(
        ...,
        description="Event start time"
    )
    end_time: datetime = Field(
        ...,
        description="Event end time"
    )
    is_all_day: bool = Field(
        default=False,
        description="Whether this is an all-day event"
    )
    is_done: bool = Field(
        default=False,
        description="Whether the event is marked as done"
    )
    recurrence_rule: str | None = Field(
        default=None,
        description="RFC 5545 recurrence rule (e.g., FREQ=WEEKLY;BYDAY=MO)"
    )
    color: str = Field(
        default="#4285F4",
        pattern=r"^#[0-9A-Fa-f]{6}$",
        description="Hex color code"
    )


class ScheduleCreate(ScheduleBase):
    """
    Model for creating a new schedule.
    
    Same as base - all required fields must be provided.
    ID is generated by the server, not provided by client.
    """
    pass


class ScheduleUpdate(BaseModel):
    """
    Model for updating a schedule.
    
    All fields are optional - only provided fields will be updated.
    This is different from ScheduleCreate where fields are required.
    """
    subject: str | None = Field(default=None, min_length=1, max_length=200)
    notes: str | None = None
    start_time: datetime | None = None
    end_time: datetime | None = None
    is_all_day: bool | None = None
    is_done: bool | None = None
    recurrence_rule: str | None = None
    color: str | None = Field(default=None, pattern=r"^#[0-9A-Fa-f]{6}$")


class Schedule(ScheduleBase):
    """
    Complete schedule model with ID and timestamps.
    
    This is what the API returns - includes server-generated fields.
    """
    id: str = Field(..., description="Unique identifier")
    created_at: datetime | None = Field(default=None, description="Creation timestamp")
    updated_at: datetime | None = Field(default=None, description="Last update timestamp")
    
    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "id": "sch_001",
                    "subject": "Team Meeting",
                    "notes": "Weekly sync",
                    "start_time": "2024-12-05T14:00:00",
                    "end_time": "2024-12-05T15:00:00",
                    "is_all_day": False,
                    "is_done": False,
                    "recurrence_rule": None,
                    "color": "#4285F4",
                    "created_at": "2024-12-04T10:00:00",
                    "updated_at": None,
                }
            ]
        }
    }
